version: '3'
services:
  appointments:
    image: abdulmanan02/project_appointments:c249a5d882f814a95885c27bc15e0f326ecb1331
    ports:
      - 7070:7070
    networks:
      - app-network

  doctors:
    image: abdulmanan02/project_doctors:f4f3dd39cecb243a7b51deb62747e78d80e36415
    ports:
      - 9090:9090
    networks:
      - app-network

  frontend:
    image: abdulmanan02/project_frontend:f4f3dd39cecb243a7b51deb62747e78d80e36415
    ports:
      - 3000:3000
    environment:
      - DOCTORS_SERVICE_URL=doctors:9090
      - APPOINTMENTS_SERVICE_URL=appointments:7070
    networks:
      - app-network

  db:
    image: abdulmanan02/project_db:1.0
    ports:
      - 3306:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
