version: '3'
services:
  appointments:
    image: abdulmanan02/project_appointments:f4044934d95cf73083544efa4606abf2bededb34
    ports:
      - 7070:7070
    networks:
      - app-network

  doctors:
    image: abdulmanan02/project_doctors:0fefb3655f36471ab04d21d06bfa74e43efe8066
    ports:
      - 9090:9090
    networks:
      - app-network

  frontend:
    image: abdulmanan02/project_frontend:0fefb3655f36471ab04d21d06bfa74e43efe8066
    ports:
      - 3000:3000
    environment:
      - DOCTORS_SERVICE_URL=doctors:9090
      - APPOINTMENTS_SERVICE_URL=appointments:7070
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
