version: '3'
services:
  appointments:
    image: abdulmanan02/project_appointments:5de4e484ca84cbaf356332f1a95a1b4bdba322cf
    ports:
      - 7070:7070
    networks:
      - app-network

  doctors:
    image: abdulmanan02/project_doctors:2be84abe595aa8cf06168aed6883c448afc954a2
    ports:
      - 9090:9090
    networks:
      - app-network

  frontend:
    image: abdulmanan02/project_frontend:88d23e515b4e72e7bdc028ce4a8000dacbe1037c
    ports:
      - 3000:3000
    environment:
      - DOCTORS_SERVICE_URL=doctors:9090
      - APPOINTMENTS_SERVICE_URL=appointments:7070
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
