version: '3'
services:
  appointments:
    image: abdulmanan02/project_appointments:711e8fd21fdf4b3280764ac583906baca256858f
    ports:
      - 7070:7070
    networks:
      - app-network

  doctors:
    image: abdulmanan02/project_doctors:711e8fd21fdf4b3280764ac583906baca256858f
    ports:
      - 9090:9090
    networks:
      - app-network

  frontend:
    image: abdulmanan02/project_frontend:711e8fd21fdf4b3280764ac583906baca256858f
    ports:
      - 3000:3000
    environment:
      - DOCTORS_SERVICE_URL=doctors:9090
      - APPOINTMENTS_SERVICE_URL=appointments:7070
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
