apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
        - name: appointments
          image: abdulmanan02/project_appointments:0fefb3655f36471ab04d21d06bfa74e43efe8066
          ports:
            - containerPort: 7070
          resources:
            limits:
              memory: "256Mi"  
              cpu: "500m"      
            requests:
              memory: "128Mi"  
              cpu: "250m"      
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7070
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 7070
            initialDelaySeconds: 20
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
