apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
        - name: doctors
          image: abdulmanan02/project_doctors:0fefb3655f36471ab04d21d06bfa74e43efe8066z  
          ports:
            - containerPort: 9090  

---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 9090  
      targetPort: 9090  
