name: Build and Push Appointments Microservice

on:
  push:
    branches:
      - main
    paths:
      - appointments/**   # Path-based filtering for changes in the appointments folder
  pull_request:
    branches:
      - main
    paths:
      - appointments/**   # Path-based filtering for changes in the appointments folder

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      # - name: Update local repository with remote changes
      #   run: git pull origin main

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Appointments Docker image
        run: |
          cd appointments
          docker build -t abdulmanan02/project_appointments:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push abdulmanan02/project_appointments:${{ github.sha }}

      - name: Changing Docker Compose
        run: |
          sed -i "s|abdulmanan02/project_appointments:[0-9a-f]\{40\}|abdulmanan02/project_appointments:${{ github.sha }}|g; s|abdulmanan02/project_appointments:1.0|abdulmanan02/project_appointments:${{ github.sha }}|g" docker-compose.yaml


      - name: Update docker-compose with new image tag
        run: |
          git config user.email "abdulmananshah02@gmail.com" 
          git config user.name "abdul-manan02"
          git add docker-compose.yaml
          git commit -m "Update appointments service image tag to ${{ github.sha }}"
          git config pull.rebase true
          git pull
          git push https://${{ secrets.ACCESSTOKEN }}@github.com/abdul-manan02/Dev-Ops_Project.git HEAD:main
