name: Build and Push doctors Microservice

on:
  push:
    branches:
      - main
    paths:
      - doctors/**   # Path-based filtering for changes in the doctors folder
  pull_request:
    branches:
      - main
    paths:
      - doctors/**   # Path-based filtering for changes in the doctors folder

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push doctors Docker image
        run: |
          cd doctors
          docker build -t abdulmanan02/project_doctors:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push abdulmanan02/project_doctors:${{ github.sha }}

      - name: Update docker-compose with new image tag
        run: |
          sed -i 's/abdulmanan02\/project_doctors:1.0/abdulmanan02\/project_doctors:${{ github.sha }}/g' docker-compose.yaml
          git config user.email "abdulmananshah02@gmail.com" 
          git config user.name "abdul-manan02"
          git add docker-compose.yaml
          git commit -m "Update doctors service image tag to ${{ github.sha }}"
          git push https://${{ secrets.ACCESSTOKEN }}@github.com/abdul-manan02/ACCESSTOKEN.git HEAD:main
