name: Build and Push frontend Microservice

on:
  push:
    branches:
      - main
    paths:
      - frontend/**   # Path-based filtering for changes in the frontend folder
  pull_request:
    branches:
      - main
    paths:
      - frontend/**   # Path-based filtering for changes in the frontend folder

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push frontend Docker image
        run: |
          cd frontend
          docker build -t abdulmanan02/project_frontend:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push abdulmanan02/project_frontend:${{ github.sha }}

      - name: Update docker-compose with new image tag
        run: |
          sed -i 's/abdulmanan02\/project_frontend:1.0/abdulmanan02\/project_frontend:${{ github.sha }}/g' docker-compose.yaml
          git add docker-compose.yaml
          git commit -m "Update frontend service image tag to ${{ github.sha }}"
          git push https://${{ secrets.ACCESSTOKEN }}@github.com/abdul-manan02/ACCESSTOKEN.git HEAD:main
